routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PagesController::class, 'home']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('banners', App\Http\Controllers\BannersController::class);
Route::get('{zip}/{street}', [ \App\Http\Controllers\BannersController::class, 'show']);
Route::post('{zip}/{street}/photos',
    [ \App\Http\Controllers\BannersController::class, 'addPhotos'])->name('store_photo_path');

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class Banner extends Model
{
    use HasFactory;

    protected $fillable = [
        'street',
        'city',
        'zip',
        'country',
        'state',
        'price',
        'description',
    ];

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    public function getPriceAttribute($price)
    {
        return '£' . number_format($price);
    }

    public function getDescriptionAttribute($description): string
    {
        return nl2br($description);
    }


    public static function locatedAt($zip, $street)
    {
        $street = str_replace('-', ' ', $street);

        return static::where(compact('zip', 'street'))->first();
    }

    public function addPhoto(Photo $photo)
    {
        return $this->photos()->save($photo);
    }
}

app/Http/Controllers/BannersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BannerRequest;
use App\Models\Banner;
use App\Models\Photo;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class BannersController extends Controller
{
    /**
     * BannersController constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('banners.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BannerRequest $request)
    {
        Banner::create($request->all());

        flash()->success('success!', 'Your banner has been created');

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($zip, $street)
    {

        $banner = Banner::locatedAt($zip, $street);

        return view('banners.show', compact('banner'));
    }

    public function addPhotos($zip, $street, Request $request)
    {
        $this->validate($request, [
            'photo' => 'required|mimes:jpg,png,jpeg'
        ]);

        $banner = Banner::locatedAt($zip, $street);

        if ($banner->user_id !== auth()->id()) {
            if ($request->ajax()) {
                return response('Nope!',403);
            }
            flash()->error('Nope!');

            return back();
        }

        $photo = Photo::fromFile($request->file('photo'))->upload();

        $banner->addPhoto($photo);

    }

//    protected function makephoto(UploadedFile $file)
//    {
//        return Photo::named($file->getClientOriginalName())->move($file);
//    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/banners/create.blade.php
@extends('layout')

@section('content')

    <h1>Selling Your Home?!</h1>

    <hr>

    <div class="row">
        <div>
            <form action="{{ route('banners.store') }}" method="POST" role="form">

                @include('banners.form')

                @include('partials.errors')

            </form>
        </div>
    </div>


@stop

resources/views/banners/form.blade.php
@inject('countries','\App\Http\Utilities\Country')

@csrf

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="street">Street</label>
            <input type="text" class="form-control" name="street" id="street" value="{{ old("street") }}" required>
        </div>

        <div class="form-group">
            <label for="city">City</label>
            <input type="text" class="form-control" name="city" id="city" value="{{ old("city") }}" required>
        </div>

        <div class="form-group">
            <label for="zip">Zip / Post Code</label>
            <input type="text" class="form-control" name="zip" id="zip" value="{{ old("zip") }}" required>
        </div>

        <div class="form-group">
            <label for="country">Country</label>
            <select name="country" id="country" class="form-control">
                @foreach($countries::all() as $country)
                    <option value="{{ $country }}">{{ $country }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="state">State</label>
            <input type="text" class="form-control" name="state" id="state" value="{{ old("state") }}" required>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label for="price">Selling Price</label>
            <input type="text" class="form-control" name="price" id="price" value="{{ old("price") }}" required>
        </div>

        <div class="form-group">
            <label for="description">Description Home</label>
            <textarea name="description" id="description" rows="9" class="form-control"
                      required>{{ old('description') }}</textarea>
        </div>
    </div>
</div>
<br>
<div>
    <button type="submit" class="btn btn-primary">Create Banner</button>
</div>

resources/views/banners/show.blade.php
@extends('layout')

@section('content')

    <div class="row">
        <div class="col-md-4">
            <h1>{{ $banner->street }} ({{ $banner->city }})</h1>
            <h3>{{ $banner->price }}</h3>

            <div class="description">{!! $banner->description !!}</div>
        </div>

        <div class="col-md-8">
            @foreach($banner->photos->chunk(4) as $set)
                <div class="row">
                    @foreach ($set as $photo)
                        <div class="col_md_3">
                            <img src="/{{ $photo->thumbnail_path }}" alt="">
                        </div>
                    @endforeach
                </div>
            @endforeach

                @if (auth()->check())
                    <form id="addmyPhotos" action="/{{ $banner->zip }}/{{ $banner->street }}/photos" class="dropzone" method="POST">
                        @csrf

                    </form>
                @endif

        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone.js"
            integrity="sha512-4p9OjnfBk18Aavg91853yEZCA7ywJYcZpFt+YB+p+gLNPFIAlt2zMBGzTxREYh+sHFsttK0CTYephWaY7I3Wbw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        Dropzone.options.addmyPhotos = {
            paramName: 'photo',
            maxFiles: 3,
            acceptedFiles: '.jpg , .png , .jpeg',
        }
    </script>
@stop