routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PagesController::class, 'home']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('banners', App\Http\Controllers\BannersController::class);
Route::get('{zip}/{street}', [ \App\Http\Controllers\BannersController::class, 'show']);
Route::post('{zip}/{street}/photos',
    [ \App\Http\Controllers\BannersController::class, 'addPhotos'])->name('store_photo_path');

resources/views/pages/home.blade.php
@extends('layout')

@section('content')

    <main class="container">
        <div class="bg-light p-5 rounded">
            <h1>Bongah</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt dolor, doloribus eius exercitationem
                facere, fugiat fugit in ipsam laboriosam magni minima provident quae reprehenderit, similique totam vel
                voluptate voluptatibus?</p>
            <a class="btn btn-lg btn-primary" href="{{ route('banners.create') }}" role="button">Create Banner
                &raquo;</a>
        </div>
    </main>

@stop